# Base configs
baseurl: "https://98glopes.github.io/fotografia-de-rua-sorocaba/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-FJCTYM3XWE"

# UI configs
title: "Fotografia de Rua - Registrando Sorocaba, SP"
subtitle: "Registros do Cotidiano Urbano em Imagens"
author: "Gabriel Lopes"
header:
 title: "Fotografia de Rua - Registrando Sorocaba, SP"
 subtitle: "by 0g.leite"
footer:
 name: ""
 bio: ""
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/0g.leite"
plugins:
  - jekyll-sitemap
